# coding: utf-8

"""
    Базовые модели для запросов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.object_info import ObjectInfo
from openapi_client import configuration


class TestObjectInfo(unittest.TestCase):
    """ObjectInfo unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
