openapi: 3.0.3
info:
  title: Базовые модели для запросов
  version: 1.0.0
servers:
- url: /
paths: {}
components:
  schemas:
    GuiToServer:
      description: Данные подключенных клиентов
      properties:
        tourismObjectType:
          $ref: '#/components/schemas/TourismObjectType'
        latitude:
          description: Широта
          type: float
        longitude:
          description: Долгота
          type: float
      type: object
    ServerToGui:
      description: Статистика от сервера
      properties:
        nearestHotels:
          description: Список ближайших КСР
          items:
            $ref: '#/components/schemas/ObjectInfo'
          type: array
        nearestCafe:
          description: Список ближайших общепитов
          items:
            $ref: '#/components/schemas/ObjectInfo'
          type: array
      type: object
    TourismObjectType:
      description: Тип туристического объекта
      enum:
      - theatre
      - ethnicCenter
      - museum
      - childrensTourism
      - cityAttractions
      - attraction
      - culturalCentre
      - shipbuilding
      - nationalPark
      - sanatorium
      - lookout
      - skiResort
      type: string
    ObjectInfo:
      description: Данные подключенных клиентов
      properties:
        name:
          description: Имя объекта
          type: string
        latitude:
          description: Широта
          type: float
        longitude:
          description: Долгота
          type: float
      type: object

