# coding: utf-8

"""
    Базовые модели для запросов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class TourismObjectType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Тип туристического объекта
    """


    class MetaOapg:
        enum_value_to_name = {
            "theatre": "THEATRE",
            "ethnicCenter": "ETHNIC_CENTER",
            "museum": "MUSEUM",
            "childrensTourism": "CHILDRENS_TOURISM",
            "cityAttractions": "CITY_ATTRACTIONS",
            "attraction": "ATTRACTION",
            "culturalCentre": "CULTURAL_CENTRE",
            "shipbuilding": "SHIPBUILDING",
            "nationalPark": "NATIONAL_PARK",
            "sanatorium": "SANATORIUM",
            "lookout": "LOOKOUT",
            "skiResort": "SKI_RESORT",
        }
    
    @schemas.classproperty
    def THEATRE(cls):
        return cls("theatre")
    
    @schemas.classproperty
    def ETHNIC_CENTER(cls):
        return cls("ethnicCenter")
    
    @schemas.classproperty
    def MUSEUM(cls):
        return cls("museum")
    
    @schemas.classproperty
    def CHILDRENS_TOURISM(cls):
        return cls("childrensTourism")
    
    @schemas.classproperty
    def CITY_ATTRACTIONS(cls):
        return cls("cityAttractions")
    
    @schemas.classproperty
    def ATTRACTION(cls):
        return cls("attraction")
    
    @schemas.classproperty
    def CULTURAL_CENTRE(cls):
        return cls("culturalCentre")
    
    @schemas.classproperty
    def SHIPBUILDING(cls):
        return cls("shipbuilding")
    
    @schemas.classproperty
    def NATIONAL_PARK(cls):
        return cls("nationalPark")
    
    @schemas.classproperty
    def SANATORIUM(cls):
        return cls("sanatorium")
    
    @schemas.classproperty
    def LOOKOUT(cls):
        return cls("lookout")
    
    @schemas.classproperty
    def SKI_RESORT(cls):
        return cls("skiResort")
