/*
 * Базовые модели для запросов
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ServerToMl
 */
public class ServerToMlTest {
    private final ServerToMl model = new ServerToMl();

    /**
     * Model tests for ServerToMl
     */
    @Test
    public void testServerToMl() {
        // TODO: test ServerToMl
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'latitude'
     */
    @Test
    public void latitudeTest() {
        // TODO: test latitude
    }

    /**
     * Test the property 'longitude'
     */
    @Test
    public void longitudeTest() {
        // TODO: test longitude
    }

    /**
     * Test the property 'coeffNearestPopularity'
     */
    @Test
    public void coeffNearestPopularityTest() {
        // TODO: test coeffNearestPopularity
    }

    /**
     * Test the property 'carAvailability'
     */
    @Test
    public void carAvailabilityTest() {
        // TODO: test carAvailability
    }

    /**
     * Test the property 'busAvailability'
     */
    @Test
    public void busAvailabilityTest() {
        // TODO: test busAvailability
    }

    /**
     * Test the property 'bigCarAvailability'
     */
    @Test
    public void bigCarAvailabilityTest() {
        // TODO: test bigCarAvailability
    }

    /**
     * Test the property 'shipAvailability'
     */
    @Test
    public void shipAvailabilityTest() {
        // TODO: test shipAvailability
    }

    /**
     * Test the property 'planeAvailability'
     */
    @Test
    public void planeAvailabilityTest() {
        // TODO: test planeAvailability
    }

    /**
     * Test the property 'theatre'
     */
    @Test
    public void theatreTest() {
        // TODO: test theatre
    }

    /**
     * Test the property 'ethnicCenter'
     */
    @Test
    public void ethnicCenterTest() {
        // TODO: test ethnicCenter
    }

    /**
     * Test the property 'museum'
     */
    @Test
    public void museumTest() {
        // TODO: test museum
    }

    /**
     * Test the property 'childrensTourism'
     */
    @Test
    public void childrensTourismTest() {
        // TODO: test childrensTourism
    }

    /**
     * Test the property 'cityAttractions'
     */
    @Test
    public void cityAttractionsTest() {
        // TODO: test cityAttractions
    }

    /**
     * Test the property 'attraction'
     */
    @Test
    public void attractionTest() {
        // TODO: test attraction
    }

    /**
     * Test the property 'culturalCentre'
     */
    @Test
    public void culturalCentreTest() {
        // TODO: test culturalCentre
    }

    /**
     * Test the property 'shipbuilding'
     */
    @Test
    public void shipbuildingTest() {
        // TODO: test shipbuilding
    }

    /**
     * Test the property 'nationalPark'
     */
    @Test
    public void nationalParkTest() {
        // TODO: test nationalPark
    }

    /**
     * Test the property 'sanatorium'
     */
    @Test
    public void sanatoriumTest() {
        // TODO: test sanatorium
    }

    /**
     * Test the property 'lookout'
     */
    @Test
    public void lookoutTest() {
        // TODO: test lookout
    }

    /**
     * Test the property 'skiResort'
     */
    @Test
    public void skiResortTest() {
        // TODO: test skiResort
    }

}
