openapi: '3.0.3'
info:
  version: '1.0.0'
  title: Базовые модели для запросов
paths: { }

components:
  schemas:
    #messages
    GuiToServer:
      description: Данные подключенных клиентов
      type: object
      properties:
        tourismObjectType:
          description: Тип туристичекого объекта
          $ref: "#/components/schemas/TourismObjectType"
        latitude:
          description: Широта
          type: float
        longitude:
          description: Долгота
          type: float
    ServerToGui:
      description: Статистика от сервера
      type: object
      properties:
        nearestHotels:
          description: Список ближайших КСР
          type: array
          items:
            $ref: "#/components/schemas/ObjectInfo"
        nearestCafe:
          description: Список ближайших общепитов
          type: array
          items:
            $ref: "#/components/schemas/ObjectInfo"
    # models
    TourismObjectType:
      description: Тип туристического объекта
      type: string
      enum:
        - theatre
        - ethnicCenter
        - museum
        - childrensTourism
        - cityAttractions
        - attraction
        - culturalCentre
        - shipbuilding
        - nationalPark
        - sanatorium
        - lookout
        - skiResort
    ObjectInfo:
      description: Данные подключенных клиентов
      type: object
      properties:
        name:
          description: Имя объекта
          type: string
        latitude:
          description: Широта
          type: float
        longitude:
          description: Долгота
          type: float

