/*
 * Базовые модели для запросов
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ObjectInfo;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ServerToGui
 */
public class ServerToGuiTest {
    private final ServerToGui model = new ServerToGui();

    /**
     * Model tests for ServerToGui
     */
    @Test
    public void testServerToGui() {
        // TODO: test ServerToGui
    }

    /**
     * Test the property 'nearestHotels'
     */
    @Test
    public void nearestHotelsTest() {
        // TODO: test nearestHotels
    }

    /**
     * Test the property 'nearestCafe'
     */
    @Test
    public void nearestCafeTest() {
        // TODO: test nearestCafe
    }

}
