/*
 * Базовые модели для запросов
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Тип туристического объекта
 */
@JsonAdapter(TourismObjectType.Adapter.class)
public enum TourismObjectType {
  
  THEATRE("theatre"),
  
  ETHNICCENTER("ethnicCenter"),
  
  MUSEUM("museum"),
  
  CHILDRENSTOURISM("childrensTourism"),
  
  CITYATTRACTIONS("cityAttractions"),
  
  ATTRACTION("attraction"),
  
  CULTURALCENTRE("culturalCentre"),
  
  SHIPBUILDING("shipbuilding"),
  
  NATIONALPARK("nationalPark"),
  
  SANATORIUM("sanatorium"),
  
  LOOKOUT("lookout"),
  
  SKIRESORT("skiResort");

  private String value;

  TourismObjectType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TourismObjectType fromValue(String value) {
    for (TourismObjectType b : TourismObjectType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<TourismObjectType> {
    @Override
    public void write(final JsonWriter jsonWriter, final TourismObjectType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TourismObjectType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TourismObjectType.fromValue(value);
    }
  }
}

